# Generated by Django 2.2.6 on 2019-12-03 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CodeConfab', '0002_remove_language_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
