# Generated by Django 2.2.6 on 2019-12-05 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeConfab', '0004_auto_20191204_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Nationality',
            new_name='nationality',
        ),
    ]
