# Generated by Django 2.2.6 on 2019-12-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeConfab', '0007_auto_20191205_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='What schools have you attended?'),
        ),
    ]
