# Generated by Django 2.2.6 on 2019-12-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeConfab', '0008_auto_20191205_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='user_base',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
