# Generated by Django 2.2.6 on 2019-12-07 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeConfab', '0009_language_user_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
