# Generated by Django 2.2.6 on 2019-12-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeConfab', '0010_auto_20191207_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='user',
            new_name='users',
        ),
    ]
