# Generated by Django 2.2.6 on 2019-12-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeConfab', '0011_auto_20191207_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='resources',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='resources/pdfs/', verbose_name='Add pdf if any'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Add a link to your resource'),
        ),
    ]
