# Generated by Django 2.2.6 on 2019-12-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeConfab', '0012_auto_20191208_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='link',
            field=models.URLField(null=True, verbose_name='Add a link to your resource'),
        ),
    ]
