# Generated by Django 2.2.6 on 2019-12-26 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CodeConfab', '0015_auto_20191226_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Describe your errors:')),
                ('code', models.TextField(verbose_name='Paste code here:')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeConfab.Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Give opinion:')),
                ('code', models.TextField(verbose_name='Paste code if any:')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeConfab.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
