# Generated by Django 2.2.6 on 2020-01-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeConfab', '0018_auto_20200115_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friend',
            field=models.ManyToManyField(blank=True, related_name='_profile_friend_+', to='CodeConfab.Profile'),
        ),
    ]
