# Generated by Django 2.2.6 on 2020-01-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeConfab', '0020_poke_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='prompted',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='prompter',
        ),
        migrations.DeleteModel(
            name='Poke',
        ),
        migrations.DeleteModel(
            name='Prompt',
        ),
    ]
