# Generated by Django 2.2.6 on 2020-02-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeConfab', '0024_auto_20200212_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='created',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=models.CharField(max_length=400, verbose_name='Reply'),
        ),
    ]
