# Generated by Django 2.2.6 on 2020-02-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeConfab', '0025_auto_20200212_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=models.CharField(max_length=400, null=True, verbose_name='Reply'),
        ),
    ]
