# Generated by Django 2.2.6 on 2020-02-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeConfab', '0027_auto_20200212_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reply',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
